name: Release to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_run:
    workflows: ["Auto Version Bump"]
    types:
      - completed
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      new_version: ${{ steps.check.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Check for version bump in package.json
        id: check
        run: |
          echo "GitHub event: ${{ github.event_name }}"
          echo "Checking package.json for version changes..."
          
          # Get current version from package.json
          NEW_VERSION=$(jq -r '.version' package.json)
          echo "Current version in package.json: $NEW_VERSION"
          
          if [ "${{ github.event_name }}" = "push" ]; then
            # For direct pushes, compare with previous commit
            echo "This is a push event - comparing with previous commit"
            git diff HEAD^ HEAD --name-only 
            
            if git diff HEAD^ HEAD --name-only | grep -q "package.json"; then
              echo "package.json was changed in this commit"
            else
              echo "package.json was not changed in this commit - exiting check"
              exit 0
            fi
            
            OLD_VERSION=$(git show HEAD^:package.json | jq -r '.version')
            echo "Previous version from HEAD^: $OLD_VERSION"
          
          elif [ "${{ github.event_name }}" = "workflow_run" ]; then
            # For workflow_run events, we'll check the commits to see if there was a version bump
            echo "This is a workflow_run event triggered by 'Auto Version Bump'"
            echo "Workflow run id: ${{ github.event.workflow_run.id }}"
            echo "Workflow run name: ${{ github.event.workflow_run.name }}"
            echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "Checking the most recent commit..."
            
            # Get the commit message of the most recent commit
            COMMIT_MSG=$(git log -1 --pretty=%B)
            echo "Most recent commit message: $COMMIT_MSG"
            
            # See if it matches the version bump pattern
            if echo "$COMMIT_MSG" | grep -q "Bump version to"; then
              echo "This appears to be a version bump commit"
              
              # Get previous version from the commit before
              OLD_VERSION=$(git show HEAD^:package.json | jq -r '.version')
              echo "Previous version from commit before bump: $OLD_VERSION"
              
              # Force version_changed to true for workflow_run events from Auto Version Bump
              echo "version_changed=true" >> $GITHUB_OUTPUT
              echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
              echo "Version will be published: $NEW_VERSION"
              exit 0
            else
              echo "This does not appear to be triggered by a version bump commit"
              echo "version_changed=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            echo "Unknown event type - cannot determine version change"
            echo "version_changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Compare versions for push events
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "Version changed from $OLD_VERSION to $NEW_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged ($OLD_VERSION == $NEW_VERSION)"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Debug build-and-release job
        run: |
          echo "========== DEBUG INFO =========="
          echo "Version changed: ${{ needs.check-version.outputs.version_changed }}"
          echo "New version: ${{ needs.check-version.outputs.new_version }}"
          echo "Event name: ${{ github.event_name }}"
          echo "================================"
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          # Use npm install instead of npm ci to ensure packages are installed correctly
          # This allows for modifications to package.json that may not be reflected in package-lock.json
          npm install
          
          # No need to install Jest globally as it's now in package.json and node_modules
        
      - name: Debug npm environment
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Listing node_modules:"
          ls -la node_modules/.bin/
          echo "Mocha package:"
          npm list mocha

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          # First try using our updated test command from package.json
          npm test || (
            # If that fails, try with explicit path to mocha
            NODE_OPTIONS="--experimental-vm-modules" ./node_modules/.bin/mocha "test/**/*.test.js"
          )

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.new_version }}
          release_name: Release v${{ needs.check-version.outputs.new_version }}
          body: |
            Release version ${{ needs.check-version.outputs.new_version }}
            
            This is an automated release created when the package.json version was updated.
          draft: false
          prerelease: false

      - name: Setup NPM Authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami || echo "Authentication failed, but continuing..."

      # Using Provenance for npm supply chain security
      # https://docs.npmjs.com/generating-provenance-statements
      - name: Publish to NPM with Provenance
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}