name: Release to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      contents: read
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      new_version: ${{ steps.check.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Check for version bump in package.json
        id: check
        run: |
          echo "GitHub event: ${{ github.event_name }}"
          echo "Checking package.json for version changes..."
          
          if [ "${{ github.event_name }}" = "push" ]; then
            # For direct pushes, compare with previous commit
            echo "This is a push event - comparing with previous commit"
            git diff HEAD^ HEAD --name-only 
            
            if git diff HEAD^ HEAD --name-only | grep -q "package.json"; then
              echo "package.json was changed in this commit"
            else
              echo "package.json was not changed in this commit - exiting check"
              exit 0
            fi
            
            OLD_VERSION=$(git show HEAD^:package.json | jq -r '.version')
            NEW_VERSION=$(jq -r '.version' package.json)
            echo "Previous version from HEAD^: $OLD_VERSION"
          else
            # For merged PRs, compare with base branch
            echo "This is a PR merge event - comparing with base branch"
            echo "Base ref: ${{ github.base_ref }}"
            
            echo "Fetching base branch..."
            git fetch origin ${{ github.base_ref }}
            
            OLD_VERSION=$(git show origin/${{ github.base_ref }}:package.json | jq -r '.version')
            NEW_VERSION=$(jq -r '.version' package.json)
            echo "Previous version from base branch: $OLD_VERSION"
          fi
          
          echo "Current version in package.json: $NEW_VERSION"
          
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "Version changed from $OLD_VERSION to $NEW_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged ($OLD_VERSION == $NEW_VERSION)"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi
          
          echo "Workflow will proceed: ${{ needs.check-version.outputs.version_changed == 'true' }}"

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          # Use npm install instead of npm ci to ensure packages are installed correctly
          # This allows for modifications to package.json that may not be reflected in package-lock.json
          npm install
          
          # No need to install Jest globally as it's now in package.json and node_modules
        
      - name: Debug npm environment
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Listing node_modules:"
          ls -la node_modules/.bin/
          echo "Mocha package:"
          npm list mocha

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          # First try using our updated test command from package.json
          npm test || (
            # If that fails, try with explicit path to mocha
            NODE_OPTIONS="--experimental-vm-modules" ./node_modules/.bin/mocha "test/**/*.test.js"
          )

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.new_version }}
          release_name: Release v${{ needs.check-version.outputs.new_version }}
          body: |
            Release version ${{ needs.check-version.outputs.new_version }}
            
            This is an automated release created when the package.json version was updated.
          draft: false
          prerelease: false

      - name: Setup NPM Authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami || echo "Authentication failed, but continuing..."

      # Using Provenance for npm supply chain security
      # https://docs.npmjs.com/generating-provenance-statements
      - name: Publish to NPM with Provenance
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}