name: Simple Release Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
      
      - name: Get version info
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version in package.json: $VERSION"
      
      - name: Build test
        run: |
          echo "Building version ${{ steps.version.outputs.version }}"
          
      - name: Create test release
        run: |
          echo "Creating release for version ${{ steps.version.outputs.version }}"
          echo "This is a test release"
      
      - name: Test complete
        run: |
          echo "✅ Simple release test complete"
          echo "Version: ${{ steps.version.outputs.version }}"